//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace phpCSBase.cwfapiService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/soap/cwf_service", ConfigurationName="cwfapiService.cwf_servicePortType")]
    public interface cwf_servicePortType {
        
        // CODEGEN: 消息 job_dataentryRequest 的包装命名空间(http://www.w1tj.com)以后生成的消息协定与默认值(http://localhost/soap/cwf_service)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/cwfapi/api.php/job_dataentry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        phpCSBase.cwfapiService.job_dataentryResponse job_dataentry(phpCSBase.cwfapiService.job_dataentryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="job_dataentry", WrapperNamespace="http://www.w1tj.com", IsWrapped=true)]
    public partial class job_dataentryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string args;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string appkey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string signed;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string updata;
        
        public job_dataentryRequest() {
        }
        
        public job_dataentryRequest(string name, string args, string username, string appkey, string signed, string updata) {
            this.name = name;
            this.args = args;
            this.username = username;
            this.appkey = appkey;
            this.signed = signed;
            this.updata = updata;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="job_dataentryResponse", WrapperNamespace="http://www.w1tj.com", IsWrapped=true)]
    public partial class job_dataentryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public job_dataentryResponse() {
        }
        
        public job_dataentryResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface cwf_servicePortTypeChannel : phpCSBase.cwfapiService.cwf_servicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class cwf_servicePortTypeClient : System.ServiceModel.ClientBase<phpCSBase.cwfapiService.cwf_servicePortType>, phpCSBase.cwfapiService.cwf_servicePortType {
        
        public cwf_servicePortTypeClient() {
        }
        
        public cwf_servicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public cwf_servicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public cwf_servicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public cwf_servicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        phpCSBase.cwfapiService.job_dataentryResponse phpCSBase.cwfapiService.cwf_servicePortType.job_dataentry(phpCSBase.cwfapiService.job_dataentryRequest request) {
            return base.Channel.job_dataentry(request);
        }
        
        public string job_dataentry(string name, string args, string username, string appkey, string signed, string updata) {
            phpCSBase.cwfapiService.job_dataentryRequest inValue = new phpCSBase.cwfapiService.job_dataentryRequest();
            inValue.name = name;
            inValue.args = args;
            inValue.username = username;
            inValue.appkey = appkey;
            inValue.signed = signed;
            inValue.updata = updata;
            phpCSBase.cwfapiService.job_dataentryResponse retVal = ((phpCSBase.cwfapiService.cwf_servicePortType)(this)).job_dataentry(inValue);
            return retVal.@return;
        }
    }
}
